### ISSUE TITLE
Snapdragon 660 GPIO PINS

### ISSUE THREAD

**Issue by harunkurtdev** [sdm660-mainline/linux#7]
I want to get the gpio pins on the mobile phone and the information of the gyro sensor, how can I do it?

**Comment by minlexx** [comment]
I don't think you can reach sensors using gpio on sdm660 platfrom, they might be "hidden" behind Snapdragn Sensor Core (but I'm not sure)

If you need to access any *ubused* GPIOs from linux userspace, you can use libgpiod  CLI tools or C API for that (or one of its [bindings](https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/tree/bindings) )

**Comment by harunkurtdev** [comment]
I want to use it with Android operating system installed, like linux operating system, but do I need to be rooted operating system, I want to use Ros/ros2 operating system.

**Comment by minlexx** [comment]
If I understand correctly, ros is based on ubuntu, there are some packages
```
$ apt search libgpiod
gpiod/jammy 1.6.3-1build1 amd64
  Tools for interacting with Linux GPIO character device - binary

libgpiod-dev/jammy 1.6.3-1build1 amd64
  C library for interacting with Linux GPIO device - static libraries and headers

libgpiod-doc/jammy,jammy 1.6.3-1build1 all
  C library for interacting with Linux GPIO device - library documentation

libgpiod2/jammy 1.6.3-1build1 amd64
  C library for interacting with Linux GPIO device - shared libraries
```
debian man page for command-line tool `gpioset` - https://manpages.debian.org/experimental/gpiod/gpioset.1.en.html
kernel must be built with `CONFIG_GPIO_CDEV`

**Comment by harunkurtdev** [comment]
a very useful website, I will do some research on this, thank you very much for sharing the resource.
